name: example-e2e-test
on: push
  # pull_request:
  #   branches:
  #    - main
  # push:
  #   branches:
  #    - main
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: KCL Installation
        run: go install ./cmd/kcl

      - name: Example tests
        shell: bash -ieo pipefail {0}
        run: PATH=$PATH:$HOME/go/bin ./examples/test.sh

      - name: run concurrent e2e
        run: PATH=$PATH:$HOME/go/bin ./scripts/concurrent_test.sh

  macos:
    strategy:
      matrix:
        os: [macos-12, macos-13, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
  
      - name: KCL Installation
        run: go install ./cmd/kcl

      - name: e2e tests
        run: PATH=$PATH:$HOME/go/bin kcl ./examples/kubernetes.k

      - name: Example tests
        shell: bash -ieo pipefail {0}
        run: PATH=$PATH:$HOME/go/bin ./examples/test.sh

      - name: run concurrent e2e
        run: PATH=$PATH:$HOME/go/bin ./scripts/concurrent_test.sh

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Make
        run: choco install make -y

      - name: KCL Installation and Tests
        shell: powershell
        run: |
          iwr -useb get.scoop.sh -outfile 'install.ps1'
          .\install.ps1 -RunAsAdmin
          scoop bucket add kcl-lang https://github.com/kcl-lang/scoop-bucket.git
          scoop install kcl-lang/kcl
          kcl.exe .\examples\kubernetes.k
          .\examples\test.ps1
